#!/bin/bash

# Called by "git push" after it has checked the remote status, but before anything has 
# been pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>

while read local_ref local_sha remote_ref remote_sha
do
  reg="^refs/heads/(feature|bugfix|experiment)/[A-Z][a-z0-9]+(-[a-z0-9]+)*$|^refs/heads/(main|develop)$"
  # Check if the branch being pushed matches the desired format
  if [[ "$local_ref" =~  $reg ]] || [[ "$remote_ref" =~  $reg ]]; then
  	exit 0
  else
    echo "Error: Local or remote branch name must be one of the following conventions: 
    feature/*,
    bugfix/*, 
    experiment/*, 
    main, 
    develop.
    The * can be any string that respects the following regular expression: [A-Z][a-z0-9]+(-[a-z0-9]+)*$
    "
    exit 1
  fi
done

exit 0
